version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysqldb
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/home/.m2
    stdin_open: true
    tty: true
  angular:
    image: sarahby/docker-angular
    container_name: docker-angular
    ports:
      - 4200:80
